'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Compras
    Public Property ID_Compras As Integer
    Public Property ID_Proveedor As Integer
    Public Property ID_Usuario As Integer
    Public Property Fecha As Date
    Public Property NumFactura As Integer
    Public Property Producto As String
    Public Property Cantidad As Integer
    Public Property Precio As Integer
    Public Property SubTotal As Integer
    Public Property Descuento As Integer
    Public Property Total As Integer

    Public Overridable Property Proveedores As Proveedores
    Public Overridable Property Usuarios As Usuarios

End Class
