'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Facturas_Prestamos
    Public Property ID_Prestamos As Integer
    Public Property ID_Cliente As Integer
    Public Property ID_Usuario As Integer
    Public Property Cedula As String
    Public Property Fecha_Prestamo As Date
    Public Property Monto As Integer
    Public Property Plazo As Integer
    Public Property Taza As Integer

    Public Overridable Property Clientes As Clientes
    Public Overridable Property Usuarios As Usuarios

End Class
