'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Data.Entity
Imports System.Data.Entity.Infrastructure

Partial Public Class JEENEntities
    Inherits DbContext

    Public Sub New()
        MyBase.New("name=JEENEntities")
    End Sub

    Protected Overrides Sub OnModelCreating(modelBuilder As DbModelBuilder)
        Throw New UnintentionalCodeFirstException()
    End Sub

    Public Overridable Property Clientes() As DbSet(Of Clientes)
    Public Overridable Property Compras() As DbSet(Of Compras)
    Public Overridable Property Facturas_Prestamos() As DbSet(Of Facturas_Prestamos)
    Public Overridable Property Proveedores() As DbSet(Of Proveedores)
    Public Overridable Property sysdiagrams() As DbSet(Of sysdiagrams)
    Public Overridable Property Tipos_Usuario() As DbSet(Of Tipos_Usuario)
    Public Overridable Property Usuarios() As DbSet(Of Usuarios)

End Class
