'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Proveedores
    Public Property ID_Proveedor As Integer
    Public Property Nombre As String
    Public Property Telefono As String
    Public Property Correo As String
    Public Property CedulaJuridica As String
    Public Property Direccion As String

    Public Overridable Property Compras As ICollection(Of Compras) = New HashSet(Of Compras)

End Class
