'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Usuarios
    Public Property ID_Usuario As Integer
    Public Property Nombre As String
    Public Property Contrasenna As String
    Public Property Usu As String
    Public Property ID_Tipo As Integer

    Public Overridable Property Compras As ICollection(Of Compras) = New HashSet(Of Compras)
    Public Overridable Property Facturas_Prestamos As ICollection(Of Facturas_Prestamos) = New HashSet(Of Facturas_Prestamos)
    Public Overridable Property Tipos_Usuario As Tipos_Usuario

End Class
